### ISSUE TITLE
DOCS: Veldnaam in huishoudelijk afval dataset klopt niet

### ISSUE THREAD

**Issue by timvanoostrom** [Amsterdam/dso-api#185]
[Deze pagina](https://api.data.amsterdam.nl/v1/docs/datasets/huishoudelijkafval.html) geeft aan dat er een `gbdBuurtId` veldnaam in de rest response voor zou moeten komen. Dit is echter niet het geval. Zie: https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/10066/

Er is wel een `gbdBuurt` property met een url erin. Deze is niet als veldnaam toegevoegd, wel als relatie.

**Comment by jjmurre** [comment]
Er is net een wat grotere aanpassing aan de DSO API geimplementeerd die deze nog beter in lijn gaat brengen met de DSO standaard (m.n. de HAL envelop (het "_links" onderdeel). Een van de afnemers van huishoudelijkafval is voor verwerking afhankelijk van het `gbdBuurtId` (dat ook in de HAL envelop zit), dus er is voor gezorgd dat dit aanwezig is in de response bodies. De nieuwe output is al te zien op acceptatie: https://acc.api.data.amsterdam.nl/v1/huishoudelijkafval/container/10066/

**Comment by timvanoostrom** [comment]
Dat betekend dus dat de docs vooruitlopen op productie?
